config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }

  resources :gardens do
  	resources :plants, only: [:new, :create]
    resources :garden_plants, except: [:edit, :update]
  end

  resources :plants, only: [:show, :index]

  namespace :admin do
    resources :plants
  end

  # resources :garden_plants, only: [:destroy], as: 'delete_garden_plant'
  get 'garden_plants/:garden_plant_id', to: 'garden_plants#show'
  get 'gardens/:garden_id/garden_plants/:garden_plant_id/water_plant', to: 'garden_plants#water_plant', as: 'water_plant'
  get 'gardens/:garden_id/plants/:id/add_garden_plant', to: 'garden_plants#add_garden_plant', as: 'add_garden_plant'
		# clean this up
end

app/models/garden.rb
class Garden < ApplicationRecord
	belongs_to :user
	has_many :garden_plants
	has_many :plants, through: :garden_plants
	validates_presence_of :name
	# accepts_nested_attributes_for :plants

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
before_action :set_garden, only: [:show, :edit, :update, :destroy]
before_action :is_owner, except: [:new, :create, :index]

	def new
		@garden = Garden.new
	end

	def create
		@garden = Garden.new(garden_params)
		@garden.user = current_user

		if @garden.save
			respond_to do |f|
			  f.json {render json: @garden}
			  f.html {redirect_to @garden}
			end
		else
			render :new
		end
	end

	def edit
	end

	def update
		@garden.update(garden_params)

		respond_to do |format|
			format.html
			format.json
		end
	end

	def show
		respond_to do |f|
			f.html
			f.json {render json: @garden}
		end
	end

	def destroy
		@garden.garden_plants.destroy_all
		@garden.destroy

		redirect_to root_path
	end

	def index
		@gardens = current_user.gardens

		respond_to do |f|
			f.html
			f.json {render json: @gardens}
		end
		# flash[:notice] = "There "
		# 	redirect_to 
			# @gardens = Garden.all
		# end
	end

	private

	def set_garden
		@garden = Garden.find(params[:id])
	end

	def is_owner
		unless @garden.user == current_user
			flash[:notice] = "You Do Not Have Permissions to View/Update This Garden"
			redirect_to root_path
		end
	end

	def garden_params
		params.require(:garden).permit(:name)
	end

end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/gardens/edit.html.erb
Edit This Garden:

<%#= render partial: 'form', locals: {:garden => @garden} %> 
<%= form_for @garden, :url => {:controller => 'gardens', :action => 'update'} do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.submit %></p>
<% end %>	

app/views/gardens/index.html.erb
<h2 class="medium-text">Select a Garden <strong>or</strong> <%= link_to "Add New Garden", new_garden_path, id: "new-garden" %></h2>
<div id="new-garden-form"></div>
<div class='alert-class'></div>
  <div class="garden-grid">
	<h2>All Gardens:</h2><br>
	<% if @gardens.count == 0 %>
	  	<div style="grid-column:1/2;grid-row:2;">You don't have any gardens yet!</div>
	<% else %>
	<div id="garden-plants" style="grid-column:1;grid-row:2;">  
	  <% @gardens.each do |garden| %>
	  	<div><a href='<%= garden_path(garden) %>' style="text-decoration:none;" class='garden-list'><%=garden.name%></a> - <%= garden.garden_plants.count %> Plants</div>
	  <% end %>
	</div>
	<div class="medium-text" style="grid-column:2;grid-row:1;"><strong>Your Plant Info:</strong></div><br>
	<div id="garden_plant_container">
<!-- 	  <div >
	  <br>
	  </div> -->
  </div>
  <div id="garden_plant_viewer" class="viewer" style="grid-column:2;grid-row:2;"> - Will Update Here - </div>
  <% end %>
</div>

app/views/gardens/show.html.erb
<div class=".alert_class"></div>
<h3 class="medium-text">Garden Name: <span data-id='<%=@garden.id%>' id='garden_name'><%= @garden.name %></span> </h3>
<div class="garden-plants">
<ul><% @garden.garden_plants.reverse.each do |gp| %>
<!-- Eventual Image <img /> -->
<li><%= link_to gp.plant.name, plant_path(gp.plant) %>, Last Watered: <%= normalize_time(gp.last_watered) %>
	- <%= link_to "View Plant", garden_garden_plant_path(@garden, gp) %>
	<% if overdue_notice(gp) %> - <%= link_to "Water Plant", water_plant_path(@garden, gp) %> - <% end %>
 	- <%= link_to "Mulch Plant", garden_garden_plant_path(@garden, gp), method: :delete, data: { confirm: 'Are you sure?' } %>

<p><%= overdue_notice(gp) %></p></li><% end %></ul>
</div>

<h3>Select a Plant to Add to Your Garden:</h3>

<%= form_tag add_garden_plant_path(@garden), :method => :get do %>
<%= collection_select :plant, :id, Plant.order('name ASC'), :id, :name %>
<%= submit_tag "Add Plant" %>
<% end %>
<h4><%= link_to "Delete This Garden and Its Plants", garden_path(@garden), method: :delete, data: { confirm: 'Are you sure?' } %></h4>
<!-- <h3>OR</h3> -->

<%#= link_to "Make a New Plant", new_garden_plant_path(@garden) %>
<!-- <br> -->

<script>
editGardenName();
</script>